# version: '3.8' (Dihapus karena sudah tidak diperlukan)

services:
  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3005/graphql
    depends_on:
      - gateway
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - perpus-network

  # API Gateway (GraphQL)
  gateway:
    build:
      # DIPERBAIKI: Context menunjuk langsung ke folder gateway
      context: ./backend/graphql-gateway
    ports:
      - "3005:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MEMBER_SERVICE_URL=http://member-service:3001
      - BOOK_SERVICE_URL=http://book-service:3002
      - LOAN_SERVICE_URL=http://loan-service:3003
      - ADMIN_SERVICE_URL=http://admin-service:3004
    depends_on:
      - member-service
      - book-service
      - loan-service
      - admin-service
    volumes:
      - ./backend/graphql-gateway:/app
      - /app/node_modules
    networks:
      - perpus-network

  # Member Service
  member-service:
    build:
      # DIPERBAIKI: Context menunjuk langsung ke folder service
      context: ./backend/member-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=iae-db
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=db_member
    depends_on:
      iae-db: { condition: service_healthy }
    volumes:
      - ./backend/member-service:/app
      - /app/node_modules
    networks:
      - perpus-network

  # Book Service
  book-service:
    build:
      # DIPERBAIKI: Context menunjuk langsung ke folder service
      context: ./backend/book-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_HOST=iae-db
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=db_books
    depends_on:
      iae-db: { condition: service_healthy }
    volumes:
      - ./backend/book-service:/app
      - /app/node_modules
    networks:
      - perpus-network

  # Loan Service
  loan-service:
    build:
      # DIPERBAIKI: Context menunjuk langsung ke folder service
      context: ./backend/loan-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DB_HOST=iae-db
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=db_loans
      - MEMBER_SERVICE_URL=http://member-service:3001
      - BOOK_SERVICE_URL=http://book-service:3002
    depends_on:
      iae-db: { condition: service_healthy }
      member-service: { condition: service_started }
      book-service: { condition: service_started }
    volumes:
      - ./backend/loan-service:/app
      - /app/node_modules
    networks:
      - perpus-network

  # Admin Service
  admin-service:
    build:
      # DIPERBAIKI: Context menunjuk langsung ke folder service
      context: ./backend/admin-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DB_HOST=iae-db
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=db_admin
    depends_on:
      iae-db: { condition: service_healthy }
    volumes:
      - ./backend/admin-service:/app
      - /app/node_modules
    networks:
      - perpus-network

  # ... (service iae-db dan phpmyadmin tetap sama seperti sebelumnya) ...
  # Database (MySQL)
  iae-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - "3307:3306"
    volumes:
      - iae-db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks: [perpus-network]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      retries: 10

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=iae-db
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
    depends_on:
      iae-db: { condition: service_healthy }
    networks:
      - perpus-network

volumes:
  iae-db-data:

networks:
  perpus-network:
    driver: bridge